In [6]:
import numpy
def arrays(arr):
    a=numpy.array(arr,float)
    return a[::-1]
arr = input().strip().split(' ')
result = arrays(arr)

1 2 3 4 -8 -10


In [7]:
import numpy as np
print(np.array(input().split(),dtype=int).reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
import numpy as np
nm=input().split()
n,m=int(nm[0]),int(nm[1])
l=[input().split() for i in range(n)]
arr=np.array(l,dtype=int)
print(np.transpose(arr))
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [ ]:
import numpy as np
m,n,p=map(int,input().split())
A=np.array([input().split() for _ in range(m)],int)
B=np.array([input().split() for _ in range(n)],int)
print(np.concatenate((A,B),axis=0))

In [ ]:
import numpy as np
a=tuple(map(int, input().split()))
print(np.zeros(a,dtype=int))
print(np.ones(a,dtype=int))

In [13]:
import numpy as np
n,m=map(int,input().split())
np.set_printoptions(sign=" ")
print(np.eye(n,m))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [12]:
import numpy as np
N,M=map(int, input().split())
A=np.array([list(map(int, input().split())) for n in range(N)])
B=np.array([list(map(int, input().split())) for n in range(N)])
print(A+B)
print(A-B)
print(A*B)
print(A//B)
print(A%B)
print(A**B)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [11]:
import numpy as np
np.set_printoptions(sign=" ")
arr=np.array(input().split(),dtype=float)
a=np.floor(arr)
b=np.ceil(arr)
c=np.rint(arr)
print(a)
print(b)
print(c)

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [10]:
import numpy as np
n,m=map(int,input().split())
a=[]
for i in range(n):
    l=list(map(int,input().split()))
    a.append(l)
b=np.array(a)
print(np.prod(np.sum(b,axis=0),axis=0))

2 2
1 2
3 4
24


In [9]:
import numpy as np
n,m=map(int,input().split())
x=np.array([input().split() for _ in range(n)],int)
print(np.max(np.min(x,axis=1),axis=0))

4 2
2 5
3 7
1 3
4 0
3


In [ ]:
import numpy as np
n,m =[int(x) for x in input().strip().split()]
a=np.array([[int(x) for x in input().strip().split()] for _ in range(n)], dtype = float)
print(np.mean(a, axis = 1))
print(np.var(a, axis = 0))
print(np.round(np.std(a),decimals=11))

In [ ]:
import numpy as np
N=int(input())
A=np.array([input().split() for _ in range(N)],int)
B=np.array([input().split() for _ in range(N)],int)
print(np.dot(A,B))

In [ ]:
import numpy as np
A=np.array(input().split(),int)
B=np.array(input().split(),int)
print(np.inner(A,B))
print(np.outer(A,B))

In [ ]:
import numpy as np
a=[float(x) for x in input().split()]
n=float(input())
print(np.polyval(a,n))